name: Cypress Tests

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Populate testing service account file
        env:
          TESTING_SERVICE_ACCOUNT_SECRET_JSON: ${{ secrets.TESTING_SERVICE_ACCOUNT_SECRET_JSON }}
        run: |
          cat <<EOF > service_account.json
          $TESTING_SERVICE_ACCOUNT_SECRET_JSON
          EOF
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Integration tests are way too slow otherwise.
          record: false
          build: yarn install
          start: yarn run ws --directory docs --port 8080
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "service_account.json"
          # Prints Javascript console messages to GitHub workflow terminal.
          ELECTRON_ENABLE_LOGGING: 1
          GITHUB_WORKFLOW: 1
        
