name: Presubmit

on:
  push:
  # Can be triggered manually.
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: yarn
      - name: Lint
        # This is ugly, but seems like the easiest way to just fetch 'master'
        # and then run the linter, which diffs against the master branch.
        run: |
          git fetch origin master --depth 1
          git checkout master
          git checkout '@{-1}'
          ./lint.sh
      - name: Populate testing service account file
        env:
          TESTING_SERVICE_ACCOUNT_SECRET_JSON: ${{ secrets.TESTING_SERVICE_ACCOUNT_SECRET_JSON }}
        run: |
          cat <<EOF > service_account.json
          $TESTING_SERVICE_ACCOUNT_SECRET_JSON
          EOF
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          start: yarn run ws --directory docs --port 8080
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "service_account.json"
          # Prints Javascript console messages to GitHub workflow terminal.
          ELECTRON_ENABLE_LOGGING: 1
          GITHUB_WORKFLOW: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
